name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - run: wget https://zig.pm/zls/downloads/wasm32-wasi/bin/zls.wasm -O src/zls.wasm

      # - run: |
      #     mkdir zigarchive
      #     cd zigarchive
      #     curl $(curl https://ziglang.org/download/index.json | jq .master.src.tarball -r) | xz -d | tar -xvf - --strip-components=1
      #     cd ..
      #     tar -cz zigarchive/lib/std > src/zig.tar.gz

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install
      
      - run: ./node_modules/.bin/parcel build --public-url /zig-playground --dist-dir docs index.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "docs"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
